# Generated by Django 3.2.8 on 2021-10-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
